### ISSUE TITLE
Production release items

### ISSUE THREAD

**Issue by low-earth-orbit** [low-earth-orbit/tennis-tune#83]
### TODO: These are items before publishing to Play Store

- [ ] Reorder racquets in the list

- [ ] Input length limit for racquet name.
- [ ] UI enhancement after audio permission is denied
- [ ] User instructions

- [ ] Review racquet list recycler view update

- [ ] Review WindowManager error message
- [ ] Code review from experienced Android developers

- [ ] Review audio processing algorithms from subject-matter experts

- [ ] Review tension calculations from subject-matter experts

- [ ] Choose a licence

---- 
### Candidates for next phase

- [ ] String type selection menu for string mass density values

- [ ] User control of the audio processing or tension calculation

- [ ] Tension and playtime tracking

- [ ] UI redesign/enhancement 

- [ ] Audio processing algorithm enhancement
